package br.uva.rsuva.model;

public enum CursoEnum {

	ADMINISTRACAO,
	CIENCIA_DA_COMPUTACAO,
	ENGENHARIA_DE_PRODUCAO,
	ENGENHARIA_MECANICA,
	ENGENHARIA_ELETRICA,
	FISIOTERAPIA,
	FOTOGRAFIA,
	HISTORIA,
	LETRAS,
	PEDAGOGIA,
	PSICOLOGIA,
	REDES_DE_COMPUTADORES,
	RELACOES_INTERNACIONAIS,
	SERVICO_SOCIAL,
	SISTEMAS_DE_INFORMACAO,
	TURISMO	
}
